const stages=[
 {title:"Profil paket",description:"Tentukan konteks paket yang ingin Anda ikuti.",intro:"Konteks pengadaan",lead:"Jawaban ini menentukan cabang pemeriksaan dan aturan sektoral yang perlu diperhatikan.",questions:[
  {id:"procurementType",label:"Jenis pengadaan yang ingin diikuti",type:"choice",required:true,options:[["barang","Barang","Produk, bahan, perangkat atau peralatan"],["konstruksi","Pekerjaan konstruksi","Bangunan, jalan, instalasi atau pekerjaan sipil"],["konsultansi","Jasa konsultansi","Kajian, desain, supervisi atau tenaga ahli"],["lainnya","Jasa lainnya","Operasional, pemeliharaan, event, TI atau layanan lain"]]},
  {id:"packageValue",label:"Perkiraan nilai paket",type:"choice",required:true,options:[["under100","Sampai Rp100 juta","Paket bernilai kecil"],["100to400","Rp100–400 juta","Periksa batas metode pengadaan"],["400to2500","Rp400 juta–2,5 miliar","Umumnya membutuhkan persaingan lebih luas"],["over2500","Di atas Rp2,5 miliar","Persyaratan kapasitas lebih tinggi"]]},
  {id:"sector",label:"Bidang utama pekerjaan",type:"select",required:true,options:[["umum","Umum"],["teknologi","Teknologi informasi"],["transportasi","Transportasi"],["konstruksi","Konstruksi"],["kesehatan","Kesehatan"],["makanan","Makanan/katering"],["keamanan","Keamanan"],["lain","Lainnya"]]}
 ]},
 {title:"Legalitas usaha",description:"Periksa identitas dan ruang lingkup usaha.",intro:"Fondasi legal",lead:"Legalitas harus aktif, benar, serta sesuai dengan bidang pekerjaan yang ditawarkan.",questions:[
  {id:"entity",label:"Bentuk pelaku usaha",type:"choice",required:true,options:[["individual","Perseorangan","Pelaku usaha perorangan"],["cv","CV","Persekutuan komanditer"],["pt","PT","Perseroan terbatas"],["cooperative","Koperasi","Badan usaha koperasi"]]},
  {id:"nib",label:"Apakah sudah memiliki NIB yang aktif?",type:"yesno",required:true},
  {id:"kbli",label:"Apakah KBLI pada NIB sesuai dengan bidang paket?",type:"yesno",required:true},
  {id:"tax",label:"Apakah NPWP dan kewajiban perpajakan tertib?",type:"yesno",required:true},
  {id:"beneficialOwner",label:"Apakah data pemilik manfaat sudah dilaporkan dan mutakhir?",type:"yesno",required:true},
  {id:"sectorLicense",label:"Apakah izin/sertifikat sektoral yang disyaratkan sudah tersedia?",type:"choice",required:true,options:[["yes","Ya","Sudah lengkap dan masih berlaku"],["no","Belum","Masih perlu dilengkapi"],["not-sure","Belum tahu","Belum membaca persyaratan paket"],["na","Tidak relevan","Tidak ada izin sektoral khusus"]]}
 ]},
 {title:"Akun pengadaan",description:"Pastikan profil elektronik siap digunakan.",intro:"Akses sistem",lead:"Data pada sistem pengadaan harus konsisten dengan dokumen asli perusahaan.",questions:[
  {id:"inaproc",label:"Apakah sudah memiliki akun penyedia INAPROC/SPSE?",type:"yesno",required:true},
  {id:"sikap",label:"Apakah profil dan dokumen pada SIKaP sudah lengkap dan terbaru?",type:"yesno",required:true},
  {id:"performance",label:"Apakah riwayat penilaian kinerja penyedia tersedia dan baik?",type:"choice",required:true,options:[["yes","Ya","Kinerja telah tercatat dan baik"],["new","Perusahaan baru","Belum memiliki riwayat"],["no","Belum","Ada kontrak tetapi belum dinilai"],["poor","Ada masalah","Pernah mendapat penilaian kurang baik"]]},
  {id:"blacklist",label:"Apakah perusahaan, pengurus, dan pihak terkait bebas dari daftar hitam?",type:"yesno",required:true}
 ]},
 {title:"Kemampuan",description:"Nilai kesiapan melaksanakan kontrak.",intro:"Kapasitas pelaksanaan",lead:"Jangan hanya mengejar kemenangan; pastikan paket dapat diselesaikan sesuai mutu, waktu, dan biaya.",questions:[
  {id:"experience",label:"Apakah memiliki pengalaman yang relevan dan dapat dibuktikan?",type:"choice",required:true,options:[["strong","Ya, kuat","Kontrak dan BAST lengkap"],["some","Sebagian","Relevan tetapi bukti belum lengkap"],["new","Belum","Perusahaan baru/belum berpengalaman"]]},
  {id:"people",label:"Apakah personel yang dipersyaratkan tersedia dan berkomitmen?",type:"yesno",required:true},
  {id:"equipment",label:"Apakah peralatan utama tersedia atau memiliki dukungan sah?",type:"yesno",required:true},
  {id:"finance",label:"Apakah arus kas cukup untuk memulai dan menjalankan pekerjaan?",type:"choice",required:true,options:[["yes","Cukup","Sudah ada perhitungan arus kas"],["tight","Terbatas","Bergantung uang muka/pembayaran cepat"],["no","Belum","Belum menghitung kebutuhan modal"]]},
  {id:"price",label:"Apakah harga sudah dihitung dari HPP, pajak, risiko, dan margin?",type:"yesno",required:true}
 ]},
 {title:"Integritas",description:"Periksa risiko yang tidak boleh dinegosiasikan.",intro:"Etika dan kepatuhan",lead:"Jawab apa adanya. Satu pelanggaran integritas dapat berujung gugur, daftar hitam, kerugian, atau pidana.",questions:[
  {id:"ownDocs",label:"Semua dokumen dan pengalaman benar-benar milik/dikuasai secara sah?",type:"yesno",required:true},
  {id:"noFlagBorrowing",label:"Perusahaan tidak meminjamkan atau meminjam 'bendera' perusahaan lain?",type:"yesno",required:true},
  {id:"noCollusion",label:"Tidak ada pengaturan harga/pemenang dengan peserta lain?",type:"yesno",required:true},
  {id:"noGift",label:"Tidak ada hadiah, komisi, atau fasilitas kepada pejabat pengadaan?",type:"yesno",required:true},
  {id:"noConflict",label:"Tidak ada konflik kepentingan dengan pihak pengadaan?",type:"choice",required:true,options:[["yes","Tidak ada","Sudah diperiksa"],["possible","Mungkin ada","Perlu deklarasi dan penilaian"],["no","Ada","Terdapat hubungan yang berisiko"]]},
  {id:"documentRead",label:"Apakah dokumen pemilihan paket sudah dibaca lengkap?",type:"choice",required:true,options:[["yes","Sudah","Termasuk rancangan kontrak"],["partial","Sebagian","Belum seluruh lampiran"],["no","Belum","Masih tahap persiapan umum"]]}
 ]}
];

const ruleBase=[
 {category:"Aturan utama",title:"Perpres Nomor 16 Tahun 2018",summary:"Kerangka dasar Pengadaan Barang/Jasa Pemerintah dari identifikasi kebutuhan sampai serah terima.",url:"https://peraturan.bpk.go.id/Details/73586/perpres-no-16-tahun-2018"},
 {category:"Aturan utama",title:"Perpres Nomor 12 Tahun 2021",summary:"Perubahan pertama atas Perpres 16/2018, termasuk penguatan peran UMK/koperasi dan penyesuaian pengadaan konstruksi.",url:"https://peraturan.bpk.go.id/Details/161828/perpres-no-12-tahun-2021"},
 {category:"Aturan utama",title:"Perpres Nomor 46 Tahun 2025",summary:"Perubahan kedua yang memperkuat PDN, mempercepat pengadaan, mengatur pemerintah desa, kinerja penyedia, serta mekanisme baru.",url:"https://peraturan.bpk.go.id/Details/318647/perpres-no-46-tahun-2025"},
 {category:"Masa transisi",title:"SE Kepala LKPP Nomor 1 Tahun 2025",summary:"Penjelasan pelaksanaan Perpres 46/2025 pada masa transisi aturan pelaksana dan penyesuaian aplikasi.",url:"https://jdih.lkpp.go.id/regulation/download/surat-edaran-kepala-lkpp-nomor-1-tahun-2025/1"},
 {category:"Pelaksanaan",title:"Peraturan LKPP Nomor 12 Tahun 2021",summary:"Pedoman pelaksanaan pengadaan melalui penyedia yang menjadi rujukan tahapan pemilihan dan kontrak sepanjang masih berlaku dan tidak bertentangan.",url:"https://peraturan.bpk.go.id/Details/169565/peraturan-lkpp-no-12-tahun-2021"},
 {category:"Pembinaan",title:"Peraturan LKPP Nomor 4 Tahun 2021",summary:"Pembinaan pelaku usaha, termasuk penilaian kinerja penyedia dan pengenaan sanksi daftar hitam.",url:"https://peraturan.bpk.go.id/Details/169556/peraturan-lkpp-no-4-tahun-2021"},
 {category:"Swakelola",title:"Peraturan LKPP Nomor 3 Tahun 2021",summary:"Pedoman swakelola: tipe, perencanaan, persiapan, pelaksanaan, pengawasan, dan serah terima.",url:"https://peraturan.bpk.go.id/Details/169555/peraturan-lkpp-no-3-tahun-2021"},
 {category:"Persaingan usaha",title:"UU Nomor 5 Tahun 1999",summary:"Melarang praktik monopoli dan persaingan usaha tidak sehat, termasuk persekongkolan untuk mengatur pemenang tender.",url:"https://peraturan.bpk.go.id/Details/45280/uu-no-5-tahun-1999"},
 {category:"Integritas",title:"UU Pemberantasan Tindak Pidana Korupsi",summary:"Dasar larangan suap, gratifikasi terkait jabatan, perbuatan curang, dan tindak pidana korupsi lainnya.",url:"https://peraturan.bpk.go.id/Details/44900/uu-no-20-tahun-2001"},
 {category:"Konstruksi",title:"UU Nomor 2 Tahun 2017",summary:"Dasar penyelenggaraan jasa konstruksi, tanggung jawab penyedia, standar keamanan, keselamatan, kesehatan, dan keberlanjutan.",url:"https://peraturan.bpk.go.id/Details/37637/uu-no-2-tahun-2017"}
];

const answers={};let currentStage=0;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function showView(id){$$(".view").forEach(v=>v.classList.toggle("active",v.id===id));$$(".nav-link").forEach(n=>n.classList.toggle("active",n.dataset.view===id));scrollTo({top:0,behavior:"smooth"})}
function choiceOptions(q){const opts=q.type==="yesno"?[["yes","Ya","Sudah tersedia atau terpenuhi"],["no","Belum","Belum tersedia atau belum terpenuhi"]]:q.options;return `<div class="option-grid">${opts.map(([v,t,d],i)=>`<div class="option"><input type="radio" id="${q.id}-${i}" name="${q.id}" value="${v}" ${answers[q.id]===v?"checked":""}><label for="${q.id}-${i}"><strong>${t}</strong><small>${d||""}</small></label></div>`).join("")}</div>`}
function renderStage(){const s=stages[currentStage];$("#stageTitle").textContent=s.title;$("#stageDescription").textContent=s.description;$("#progressText").textContent=`${currentStage+1} dari ${stages.length}`;$("#progressBar").style.width=`${(currentStage+1)/stages.length*100}%`;$("#stepper").innerHTML=stages.map((x,i)=>`<li class="${i===currentStage?"active":i<currentStage?"done":""}"><span>${i<currentStage?"✓":i+1}</span>${x.title}</li>`).join("");$("#questions").innerHTML=`<div class="question-head"><span class="counter">TAHAP ${currentStage+1} / ${stages.length}</span><h1>${s.intro}</h1><p>${s.lead}</p></div>`+s.questions.map(q=>`<fieldset class="question-group"><legend>${q.label} ${q.required?'<span class="required">*</span>':""}</legend>${q.type==="select"?`<div class="field"><select name="${q.id}"><option value="">Pilih jawaban</option>${q.options.map(([v,t])=>`<option value="${v}" ${answers[q.id]===v?"selected":""}>${t}</option>`).join("")}</select></div>`:choiceOptions(q)}</fieldset>`).join("");$("#prevBtn").style.visibility=currentStage===0?"hidden":"visible";$("#nextBtn").textContent=currentStage===stages.length-1?"Lihat hasil →":"Berikutnya →"}
function saveStage(){const missing=[];stages[currentStage].questions.forEach(q=>{const el=document.querySelector(`[name="${q.id}"]:checked`)||document.querySelector(`select[name="${q.id}"]`);if(el?.value)answers[q.id]=el.value;else if(q.required)missing.push(q.label)});$(".error-message")?.remove();if(missing.length){$("#questions").insertAdjacentHTML("afterbegin",`<div class="error-message">Lengkapi ${missing.length} pertanyaan sebelum melanjutkan.</div>`);return false}localStorage.setItem("pakarPbjpAnswers",JSON.stringify(answers));return true}
function analyze(){const rec=[];const add=(id,status,title,text,category="Umum")=>rec.push({id,status,title,text,category});
 [["nib","NIB belum aktif","Aktifkan NIB melalui OSS dan pastikan data perusahaan konsisten."],["kbli","KBLI belum sesuai","Tambahkan atau sesuaikan KBLI sebelum mengikuti paket; jangan hanya mengandalkan uraian usaha."],["tax","Kepatuhan pajak belum siap","Selesaikan administrasi dan kewajiban perpajakan sebelum kualifikasi."],["beneficialOwner","Pemilik manfaat belum mutakhir","Perbarui data pemilik manfaat sesuai kondisi pengendalian perusahaan."],["inaproc","Akun pengadaan belum tersedia","Daftar akun penyedia dan lakukan verifikasi pada sistem pengadaan."],["sikap","Profil SIKaP belum lengkap","Unggah dan mutakhirkan legalitas, pengalaman, personel, peralatan, serta data kinerja."],["blacklist","Status daftar hitam bermasalah","Jangan mengikuti pemilihan sebelum memastikan status dan ruang lingkup sanksi."],["people","Personel belum tersedia","Pastikan ketersediaan, kompetensi, dan komitmen tertulis personel."],["equipment","Peralatan belum tersedia","Siapkan bukti kepemilikan, sewa, atau dukungan peralatan yang sah."],["price","Harga belum dihitung lengkap","Hitung HPP, pajak, risiko, biaya modal, overhead, dan margin sebelum menawar."]].forEach(([id,t,x])=>add(id,answers[id]==="yes"?"ready":id==="blacklist"?"critical":"warning",answers[id]==="yes"?t.replace(/belum|bermasalah/gi,"siap"):t,answers[id]==="yes"?"Komponen ini telah dinyatakan siap. Tetap cocokkan dengan dokumen pemilihan.":x,"Kesiapan"));
 if(answers.sectorLicense==="no"||answers.sectorLicense==="not-sure")add("sectorLicense","critical","Izin sektoral belum dipastikan","Identifikasi izin, sertifikat badan usaha, sertifikat personel, atau standar khusus yang diminta paket.","Legalitas");
 if(answers.performance==="poor")add("performance","critical","Riwayat kinerja perlu ditangani","Pelajari penilaian sebelumnya dan pastikan tidak ada sanksi atau kelemahan berulang.","Kinerja");
 if(answers.experience!=="strong")add("experience",answers.experience==="new"?"warning":"warning","Bukti pengalaman belum kuat","Inventarisasi kontrak, BAST, referensi, dan kesesuaian lingkup. Periksa pengecualian yang sah bagi usaha baru.","Kualifikasi");
 if(answers.finance!=="yes")add("finance",answers.finance==="no"?"critical":"warning","Arus kas berisiko","Buat proyeksi kas berdasarkan termin, uang muka, retensi, pajak, dan keterlambatan pembayaran.","Keuangan");
 [["ownDocs","Dokumen tidak sepenuhnya sah","Hentikan proses dan verifikasi seluruh dokumen; informasi palsu dapat memicu sanksi."],["noFlagBorrowing","Risiko pinjam bendera","Jangan menggunakan badan usaha atau pengalaman pihak lain secara tidak sah."],["noCollusion","Risiko persekongkolan","Hentikan komunikasi pengaturan harga, peserta pendamping, atau pemenang."],["noGift","Risiko gratifikasi/suap","Jangan memberikan uang, hadiah, komisi, atau fasilitas terkait proses pengadaan."]].forEach(([id,t,x])=>add(id,answers[id]==="yes"?"ready":"critical",answers[id]==="yes"?t.replace("Risiko ","Bebas risiko ").replace("tidak sepenuhnya sah","telah dikonfirmasi sah"):t,answers[id]==="yes"?"Jawaban menunjukkan kepatuhan integritas. Pertahankan bukti dan dokumentasi.":x,"Integritas"));
 if(answers.noConflict!=="yes")add("noConflict","critical","Konflik kepentingan harus diselesaikan","Deklarasikan dan minta penilaian tertulis; jangan melanjutkan dengan asumsi konflik dapat diabaikan.","Integritas");
 if(answers.documentRead!=="yes")add("documentRead","warning","Dokumen pemilihan belum dibaca lengkap","Baca persyaratan kualifikasi, teknis, harga, jadwal, rancangan kontrak, serta seluruh lampiran.","Paket");
 if(answers.procurementType==="konstruksi")add("construction","warning","Lakukan pemeriksaan khusus konstruksi","Verifikasi SBU, SKK, K3, peralatan, personel manajerial, kemampuan dasar, dan ketentuan Kementerian PU.","Sektoral");
 if(["teknologi","transportasi","kesehatan","makanan","keamanan"].includes(answers.sector))add("sector","warning","Terapkan aturan sektoral tambahan",`Bidang ${answers.sector} dapat memerlukan izin, standar, keamanan, atau kompetensi khusus di luar aturan umum PBJP.`,"Sektoral");
 return rec}
function renderResult(){const rec=analyze(),crit=rec.filter(x=>x.status==="critical").length,warn=rec.filter(x=>x.status==="warning").length,ready=rec.filter(x=>x.status==="ready").length;let score=Math.max(0,Math.round((ready/(rec.length||1))*100-crit*5));if(crit)score=Math.min(score,69);$("#scoreValue").textContent=score;$("#scoreRing").style.setProperty("--score",score);$("#criticalCount").textContent=crit;$("#warningCount").textContent=warn;$("#readyCount").textContent=ready;$("#scoreLabel").textContent=score>=85?"Siap dengan verifikasi akhir":score>=70?"Cukup siap":score>=50?"Perlu perbaikan":"Belum siap mengikuti paket";$("#scoreSummary").textContent=crit?`Selesaikan ${crit} hambatan kritis sebelum memasukkan penawaran.`:"Tidak ada hambatan kritis dari jawaban Anda; tetap lakukan pemeriksaan dokumen paket.";const filters=[["all","Semua"],["critical","Kritis"],["warning","Perbaikan"],["ready","Siap"]];$("#resultFilters").innerHTML=filters.map(([v,t],i)=>`<button class="${i?"":"active"}" data-filter="${v}">${t}</button>`).join("");const draw=f=>{$("#recommendations").innerHTML=rec.filter(x=>f==="all"||x.status===f).map(x=>`<article class="recommendation ${x.status}"><span class="stat-icon ${x.status==="critical"?"danger":x.status==="warning"?"warning":"good"}">${x.status==="ready"?"✓":"!"}</span><div><span class="tag">${x.category}</span><h3>${x.title}</h3><p>${x.text}</p></div></article>`).join("")||"<p>Tidak ada item pada kategori ini.</p>"};draw("all");$$("[data-filter]").forEach(b=>b.onclick=()=>{$$("[data-filter]").forEach(x=>x.classList.remove("active"));b.classList.add("active");draw(b.dataset.filter)});const labels={barang:"Barang",konstruksi:"Pekerjaan konstruksi",konsultansi:"Jasa konsultansi",lainnya:"Jasa lainnya",under100:"≤ Rp100 juta","100to400":"Rp100–400 juta","400to2500":"Rp400 juta–2,5 miliar",over2500:"> Rp2,5 miliar"};$("#profileSummary").innerHTML=`<h4>Jenis pengadaan</h4><p>${labels[answers.procurementType]||"-"}</p><h4>Nilai paket</h4><p>${labels[answers.packageValue]||"-"}</p><h4>Bidang</h4><p>${answers.sector||"-"}</p><h4>Waktu pemeriksaan</h4><p>${new Date().toLocaleString("id-ID")}</p>`;showView("result")}
function renderRules(){const cats=[...new Set(ruleBase.map(r=>r.category))];$("#ruleCategory").innerHTML='<option value="all">Semua kategori</option>'+cats.map(c=>`<option>${c}</option>`).join("");const draw=()=>{const q=$("#ruleSearch").value.toLowerCase(),c=$("#ruleCategory").value;$("#ruleList").innerHTML=ruleBase.filter(r=>(c==="all"||r.category===c)&&`${r.title} ${r.summary}`.toLowerCase().includes(q)).map(r=>`<article class="rule-card"><span class="category">${r.category}</span><div><h3>${r.title}</h3><p>${r.summary}</p></div><a href="${r.url}" target="_blank" rel="noreferrer">Naskah resmi ↗</a></article>`).join("")||"<p>Aturan tidak ditemukan.</p>"};$("#ruleSearch").oninput=draw;$("#ruleCategory").onchange=draw;draw()}
function searchPortal(term){renderRules();showView("rules");$("#ruleSearch").value=term;$("#ruleSearch").dispatchEvent(new Event("input"));$("#ruleSearch").focus()}
function analyzePackage(form){const data=new FormData(form),available=["rup","selectionDoc","spec","contract","qualification","cost"].filter(k=>data.has(k)),missing=[];const labels={rup:"Verifikasi paket dan jadwal pada SIRUP.",selectionDoc:"Unduh dokumen pemilihan beserta seluruh lampiran.",spec:"Petakan spesifikasi teknis/KAK menjadi matriks kepatuhan.",contract:"Baca rancangan kontrak, termin, denda, jaminan, dan risiko.",qualification:"Petakan persyaratan kualifikasi dan bukti pendukung.",cost:"Hitung HPP, pajak, modal kerja, risiko, dan margin."};Object.keys(labels).filter(k=>!available.includes(k)).forEach(k=>missing.push(labels[k]));if(data.get("packageType")==="konstruksi")missing.push("Lakukan pemeriksaan khusus SBU, SKK, K3, personel, dan peralatan konstruksi.");if(data.get("packageRange")==="enterprise")missing.push("Lakukan reviu kapasitas keuangan, pengalaman, dan risiko kontrak bernilai besar.");const score=Math.round(available.length/6*100),decision=!data.has("integrity")?"stop":score>=84?"go":score>=50?"improve":"stop";const decisionText={go:"SIAP UNTUK REVIU AKHIR",improve:"PERBAIKI SEBELUM MELANJUTKAN",stop:"BELUM SIAP / NO-GO"};const out=$("#packageOutput");out.className="package-output";out.innerHTML=`<p class="eyebrow">Hasil analisis awal</p><div class="package-score"><strong>${score}</strong><span>/100<br>Kelengkapan informasi</span></div><h2>${data.get("packageName")}</h2><p>${data.get("agency")||"Instansi belum dicantumkan"} · ${data.get("packageType")}</p><div class="decision ${decision}">${decisionText[decision]}</div><h3>Prioritas berikutnya</h3><ul>${(missing.length?missing:["Seluruh informasi awal tersedia. Cocokkan bukti dengan dokumen pemilihan dan lanjutkan reviu independen."]).map(x=>`<li>${x}</li>`).join("")}</ul><p class="microcopy">Hasil beta ini bukan penetapan lulus/gugur dan belum membaca dokumen paket.</p>`}
$$("[data-view], [data-view-link]").forEach(b=>b.onclick=()=>{const v=b.dataset.view||b.dataset.viewLink;if(v==="assessment")renderStage();if(v==="rules")renderRules();showView(v)});$$("[data-start]").forEach(b=>b.onclick=()=>{renderStage();showView("assessment")});$("#nextBtn").onclick=()=>{if(!saveStage())return;if(currentStage<stages.length-1){currentStage++;renderStage();scrollTo({top:0,behavior:"smooth"})}else renderResult()};$("#prevBtn").onclick=()=>{saveStage();currentStage=Math.max(0,currentStage-1);renderStage()};$("#restartBtn").onclick=()=>{Object.keys(answers).forEach(k=>delete answers[k]);localStorage.removeItem("pakarPbjpAnswers");currentStage=0;renderStage();showView("assessment")};$("#printBtn").onclick=()=>print();try{Object.assign(answers,JSON.parse(localStorage.getItem("pakarPbjpAnswers")||"{}"))}catch{}renderRules();const initialView=location.hash.slice(1);if(["rules","assessment","analyzer"].includes(initialView)){if(initialView==="assessment")renderStage();if(initialView==="rules")renderRules();showView(initialView)}
$("#portalSearchBtn").onclick=()=>searchPortal($("#portalSearch").value);$("#portalSearch").onkeydown=e=>{if(e.key==="Enter")searchPortal(e.currentTarget.value)};$$("[data-search-topic]").forEach(b=>b.onclick=()=>searchPortal(b.dataset.searchTopic));$("#packageForm").onsubmit=e=>{e.preventDefault();if(!e.currentTarget.reportValidity())return;analyzePackage(e.currentTarget)};
